### PR TITLE
Update to HTTPS

### PR DESCRIPTION
**Pull request by homebysix**
I tested the modified recipes with `autopkg run --check` but you may want to do the same just to be sure.

### CODE REVIEW

**Comment by homebysix** [comment]
Hi @tallfunnyjew - still maintaining this repo?

**Comment by homebysix** [comment]
Closed in favor of: https://github.com/autopkg/tallfunnyjew-recipes/pull/22

**Comment by tallfunnyjew** [comment]
i am, but far less frequently, due to COVID and a child at home, @homebysix

**Comment by tallfunnyjew** [comment]
Thanks for the assist.

**Pull request closed without merging**
