### PR TITLE
add code sig verif, sanitize AppleScript and dist tomfoolery

### PR DESCRIPTION
**Pull request by arubdesu**
make pkging great again, change munki to use newly sanitized pkg recipe - doesn't try to add login items

### CODE REVIEW

**Comment by arubdesu** [comment]
Hey David, had a chance to look at this yet? Thanks.

**Comment by arubdesu** [comment]
Waddaya say?

**Comment by arubdesu** [comment]
Hey David, just checking back in.

**Comment by homebysix** [comment]
Shoot, I stepped on your .gitignore. You might have to modify that file to make the merge gods happy.

**Review by tallfunnyjew — APPROVED** [review]
sorry for the delay. not sure how to do a merge now!

**Comment by tallfunnyjew** [comment]
apologies for the delay, my good man! not quite sure how to merge as github ain't be letting me do it from the website

**Comment by homebysix** [comment]
If @arubdesu merges [this PR](https://github.com/arubdesu/tallfunnyjew-recipes/pull/1) first, I think this conflict should be resolved. Fingers crossed.

**Comment by arubdesu** [comment]
Ok, LGTM :shipit:

**Comment by tallfunnyjew** [comment]
Boom.

**Pull request merged**
